# Logger
[logger]
    Path        = "/data/site_log/51cto.com/canal/log"
    Level       = "DEV" #DEV | PROD
    Stdout      = true  #false

#Sourse Database
[source]
    Addr = "rm-2zejg15af6d9b2r9y.mysql.rds.aliyuncs.com:3306"
    User = "admin_root"
    Password = "Y0yeWjaAqkLZIb8xH9xt"
    IncludeTableRegex = [
        "edu_center\\.course",
    ]
    [source.startPos]
        Name = ""
        Pos = 0

#Notify
[notify]
    Urls = ["http://linetest.b.edu.51cto.com/site/test/index"]
