# HTTP Server
[server]
	Address     = ":8989"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "./tmp/log/server"
	AccessLogEnabled = true

# Logger.
[logger]
    Path        = "./tmp/log"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "./tmp/log/sql"
        Level  = "all"
        Stdout = true